version: '3'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: dumbstored
      POSTGRES_PASSWORD: dumbstored
      POSTGRES_DATABASE: dumbstored
  dumbstored:
    image: dumbstored
    restart: always
    environment:
      DUMBSTORED_PORT: 8080
      DUMBSTORED_ALLOW_REGISTRATION: "true"
    depends_on: 
      - db
    volumes:
      - ./dumbstored_volume:/var/dumbstored
    ports:
      - 8080:8080
